services:
  dns:
    image: dns
    build: services/bind9
    volumes:
      - ./services/bind9/conf/named.conf.options:/etc/bind/named.conf.options
      - ./services/bind9/conf/named.conf.local:/etc/bind/named.conf.local
      - ./services/bind9/conf/db.dns-local-playground.com:/etc/bind/zones/db.dns-local-playground.com
    networks:
      test-dns:
        ipv4_address: 173.21.0.2

  host1:
    image: host
    build: services/host
    networks:
      test-dns:
        ipv4_address: 173.21.0.3
    dns:
      173.21.0.2
  
  host2:
    image: host
    build: services/host
    networks:
      test-dns:
        ipv4_address: 173.21.0.4
    dns:
      173.21.0.2

networks:
  test-dns:
    driver: bridge
    ipam:
     config:
       - subnet: 173.21.0.0/16
         gateway: 173.21.0.1
